### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by tswhitworth** [robert-daniels/CartBuilder#14]
Where can I find the 1000 rows of data that we are planning on loading into our db? 

post link below thx

- Tom

**Comment by tswhitworth** [comment]
Or you can post the data it self whatever's easiest

**Comment by robert-daniels** [comment]
https://github.com/robert-daniels/CartBuilder/blob/main/RecipeNLG_Truncated.csv this merged to main this pm. May need to pull to true up your local. Sqlizer.io will covert to .sql

**Comment by tswhitworth** [comment]
Thanks.
