### ISSUE TITLE
API guys - Ad hoc notation ok?

### ISSUE THREAD

**Issue by robert-daniels** [robert-daniels/CartBuilder#16]
Building some quick mockups per discussion. Please see snip below. Before I start building components, are you guys ok with the :? and P:? notation symbolizing query placeholder for GET and POST? 

![Capture](https://user-images.githubusercontent.com/11677947/218798353-4e6e6a8c-ef15-4309-8c60-e296a1a16923.JPG)

**Comment by dghighfill** [comment]
:? and P:?  could you elaborate on this?  Was this a standard you had found?

**Comment by robert-daniels** [comment]
@dghighfill Ad hoc defined in this case is "improvised." We're building page mockups which will help inform what requests front end will be tossing to the api tier so they can start building. It's just a quick notation to mark on the screens the components that would be rendering and what they might be looking for.

**Comment by robert-daniels** [comment]
closing issue, no longer relevant
