### ISSUE TITLE
Discord server for weekly meetings and/or asynchronous team discussions

### ISSUE THREAD

**Issue by tswhitworth** [robert-daniels/CartBuilder#21]
I setup a discord server for the team. (meaning I haven't shared this link with anyone except the team)

I thought we could setup 1 meeting a week where we could meet for 15 or 20 minutes all together and discuss what we have worked on that week, and what we need help with to move forward before meet again in class.

Since we have class on Mondays, maybe we could shoot for around Thursday evenings? 

Let me know what you guys think, any day works for me in the evenings.

@robert-daniels 
@yassine022 
@ArcadeZeus 

Discord server: https://discord.gg/TcXZS5AB

**Comment by robert-daniels** [comment]
Closing, no longer relevant
