### ISSUE TITLE
[Time Sensitive] Team Jira Board

### ISSUE THREAD

**Issue by robert-daniels** [robert-daniels/CartBuilder#22]
Looking at the prof's prompt, he is wanting a different owner between the repo and jira project. The current board is set up Agile, https://robertdaniels.atlassian.net/jira/software/projects/CAR/boards/1. If anyone else is willing, can they please reproduce the board and add the team? I can dm the e-mail addresses. @yassine022 , @tswhitworth , @ArcadeZeus

**Comment by tswhitworth** [comment]
I will take this. I'm making it as we speak.

**Comment by robert-daniels** [comment]
Great, it's really appreciated!
