### ISSUE TITLE
Class Based View Django Learning Material

### ISSUE THREAD

**Issue by tswhitworth** [robert-daniels/CartBuilder#31]
Class Based Views:

In a Django app, views are typically connected to the rest of the app using the URL routing mechanism. The URL routing maps incoming URLs to specific views, allowing the views to handle the request and return the appropriate response. The URL routing can also include parameters, allowing views to retrieve specific data based on the URL parameters.

A view might retrieve data from a database using a model, and then pass that data to a template for rendering. The template might then use the data to generate HTML content, which is returned to the user as an HTTP response.

For example, you may want to implement a view that allows users to add their favorite recipes to their personal recipe collection. Here's an example of how you can do that:

**forms.py (define a form that allows users to add a new recipe):**
```python
from django import forms

class AddRecipeForm(forms.Form):
    recipe_name = forms.CharField(label='Recipe Name', max_length=100)
    ingredient_names = forms.CharField(label='Ingredients', widget=forms.Textarea)
```

This form simply includes two fields: recipe_name and ingredient_names. The ingredient_names field is a Textarea widget that allows users to enter multiple ingredients, one per line.

**views.py (define a class-based view that inherits from FormView):**
```python
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib import messages

from .forms import AddRecipeForm
from .models import Recipe, Ingredient


class AddRecipeView(FormView):
    template_name = 'add_recipe.html'
    form_class = AddRecipeForm
    success_url = reverse_lazy('recipe_list')

    def form_valid(self, form):
        # Get the current user's profile
        profile = Profile.objects.get(profile_id=self.request.user.id)

        # Get the form data
        recipe_name = form.cleaned_data['recipe_name']
        ingredient_names = form.cleaned_data['ingredient_names']

        # Create a new recipe
        recipe = Recipe.objects.create(
            profile_id=profile,
            recipe_name=recipe_name
        )

        # Add ingredients to the recipe
        for ingredient_name in ingredient_names:
            ingredient, _ = Ingredient.objects.get_or_create(name=ingredient_name)
            recipe.ingredients.add(ingredient)

        # Save the recipe and return a success message
        recipe.save()
        messages.success(self.request, f"{recipe_name} has been added to your personal recipe collection.")
        return super().form_valid(form)


def recipe_list(request):
    # Get the current user's profile
    profile = Profile.objects.get(profile_id=request.user.id)

    # Get the user's favorite recipes
    favorite_recipes = Recipe.objects.filter(profile_id=profile)

    # Render the template with the list of favorite recipes
    return render(request, 'recipe_list.html', {'favorite_recipes': favorite_recipes})
```
**form_valid view:**

This view defines a form_valid method that handles form submissions. When the form is submitted, the view creates a new Recipe object and sets its profile_id to the current user's Profile object. It then extracts the recipe_name and ingredient_names data from the form and uses them to create a new Recipe object with the appropriate fields.

Finally, it loops through each ingredient_name and retrieves the corresponding Ingredient object from the database (or creates a new one if it doesn't exist yet). It then adds each Ingredient object to the Recipe object's ingredients ManyToManyField.

Once the Recipe object has been created and all its fields have been set, it is saved to the database and a success message is displayed to the user.

**recipe_list view: (will be used for redirecting after form submission)**

The recipe_list view retrieves the user's Profile object and filters the Recipe objects by the user's profile. It then passes the list of favorite recipes to the recipe_list.html template, which can be defined as follows:

**recipe_list.html:**

```python
{% extends "base.html" %}


{% block content %}
  <h1>My Favorite Recipes</h1>
  <ul>
    {% for recipe in favorite_recipes %}
      <li>{{ recipe.recipe_name }}</li>
    {% empty %}
      <li>You don't have any favorite recipes yet.</li>
    {% endfor %}
  </ul>
{% endblock %}
```

This template extends a base.html template and defines a block of content that displays the list of favorite recipes. If the user doesn't have any favorite recipes, a message is displayed instead.

**urls.py (define a URL pattern that maps to the AddRecipeView):**

```python
from django.urls import path
from .views import AddRecipeView

urlpatterns = [
    path('add_recipe/', AddRecipeView.as_view(), name='add_recipe'),
    path('recipes/', recipe_list, name='recipe_list'),
    # ... other URL patterns ...
]
```

Now, when a user visits the /add_recipe/ URL, they will see a form that allows them to add a new recipe to their personal collection. When they submit the form, the data is validated and a new Recipe object is created and saved to the database with the appropriate fields. The user is then redirected to the recipe_list URL (which could be a view that displays a list of all the user's personal recipes).

The redirect happens in the form_valid() method of the AddRecipeView class in the views.py file. The success_url attribute is set to 'recipe_list', which is the name of a URL pattern that maps to another view.

When form_valid() is called and the form is successfully validated, it returns a HttpResponseRedirect object that redirects the user to the URL specified by success_url. The reverse_lazy() function is used to reverse the URL pattern name into an actual URL.

Finally, when the user visits the /recipes/ URL, they will see a list of their favorite recipes. If they want to add a new recipe, they can visit the /add_recipe/ URL and submit the form. Once the form is submitted, the user will be redirected to the recipe_list URL to see their updated list of favorite recipes.

**Comment by tswhitworth** [comment]
I hope this will give you guys enough examples to understand how Class Based Views work.

Please also start watching this series on Django Class Based Views: (I've watched about half of the playlist so far, best on youtube for this subject):

[Django Class-Based Views Youtube Playlist](https://www.youtube.com/playlist?list=PLOLrQ9Pn6caxNb9eFZJ6LfY29nZkKmmXT)

Class Based-Views touch a lot of different parts of our project, and that's why we all need to be familiar with them and know how to implement them from start to end, so then you can delegate work, or know what to change if need be.

Other Class-Based Views Resources:

- https://docs.djangoproject.com/en/4.1/topics/class-based-views/
- https://django-advanced-training.readthedocs.io/en/latest/features/class-based-views/
- https://ccbv.co.uk/

@robert-daniels 
@yassine022 
@ArcadeZeus

**Comment by robert-daniels** [comment]
Closing issue, no longer relevant
