### ISSUE TITLE
Backend Django Error that Tom needs help with

### ISSUE THREAD

**Issue by tswhitworth** [robert-daniels/CartBuilder#32]
I am going to show the two files that are working together to generate a user, and I will show the error that I am stuck on.

For an overview, the **factory.py** file defines factory classes that can be used to generate instances of Django model classes with random or specified data, and the **gen_user.py** file uses these factories to generate data for a new user profile.

(Note these files interact with our models.py file, which won't be present below but can be found [here](https://github.com/robert-daniels/CartBuilder/blob/test-vue-factory-testing/CartBuilderApplication/CartBuilder/models.py)

**factory.py** file defines several factory classes using the factory_boy package. These factory classes are used to create instances of Django model classes. For example, AllergyFactory is a factory class for the Allergy model class. When a new Allergy instance is created using this factory, it will randomly select one of the top ten allergic ingredients stored in the TopTenMockAllergicIngredients model class to use as the allergy_name attribute.

The RecipeFactory class is a bit more complicated. It is used to create instances of the Recipe model class, and it has several post-generation hooks that modify the new instance after it has been created. For example, the ingredients post-generation hook is used to add ingredients to the recipe. If the extracted argument is provided, it will add those specific ingredients to the recipe. Otherwise, it will choose a random MockRecipe instance and add all of its ingredients to the recipe.

The ProfileFactory class is similar, but it is used to create instances of the Profile model class. It has several post-generation hooks that modify the new instance after it has been created. For example, the allergies post-generation hook is used to add allergies to the profile. If the extracted argument is provided, it will add those specific allergies to the profile. Otherwise, it will randomly create up to three allergies using the AllergyFactory.

**factory.py:**
```python
import random
import factory
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from .models import MockRecipe, MockIngredient, MockAllergicIngredient, TopTenMockAllergicIngredients
from .models import Ingredient, Recipe, Allergy, Profile, RecipeIngredient, RecipeFavorite, MockRecipe


class AllergyFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Allergy

    @factory.lazy_attribute
    def allergy_name(self):
        top_ten_allergic_ingredients = TopTenMockAllergicIngredients.objects.all()
        if top_ten_allergic_ingredients:
            random_allergic_ingredient = random.choice(top_ten_allergic_ingredients)
            return random_allergic_ingredient.allergic_ingredient.m_allergic_ingredient


class RecipeFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Recipe

    date_created = factory.Faker('date_this_year')

    @factory.lazy_attribute
    def recipe_name(self):
        mock_recipe = MockRecipe.objects.order_by('?').first()  # get a random MockRecipe
        return mock_recipe.m_recipe_name

    @factory.post_generation
    def ingredients(self, create, extracted):
        if not create:
            return

        if extracted:
            for ingredient in extracted:
                self.ingredients.add(ingredient)
        else:
            mock_recipe = MockRecipe.objects.order_by('?').first()  # get a random MockRecipe
            for ingredient in mock_recipe.m_ingredients.all():
                self.ingredients.add(ingredient)

    @factory.post_generation
    def allergic_ingredients(self, create, extracted):
        if not create:
            return

        if extracted:
            for allergic_ingredient in extracted:
                self.allergic_ingredients.add(allergic_ingredient)
        else:
            allergic_ingredients = MockAllergicIngredient.objects.order_by('?')[:3]  # Get 3 random allergic ingredients
            for allergic_ingredient in allergic_ingredients:
                self.allergic_ingredients.add(allergic_ingredient)

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        # Override the default _create method to create the RecipeIngredient objects
        recipe = super()._create(model_class, *args, **kwargs)

        mock_recipe = MockRecipe.objects.order_by('?').first()  # get a random MockRecipe
        recipe_ingredients = [RecipeIngredient(recipe=recipe, ingredient=ing) for ing in
                              mock_recipe.m_ingredients.all()]
        RecipeIngredient.objects.bulk_create(recipe_ingredients)

        # Add allergic ingredients to the recipe
        recipe.add_allergic_ingredients()

        return recipe


class ProfileFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Profile

    random.seed(random.random())  # Set random seed for deterministic results

    profile_first_name = factory.Faker('first_name')
    profile_last_name = factory.Faker('last_name')

    @factory.post_generation
    def allergies(self, create, extracted):
        if not create:
            return

        if extracted:
            allergies = list(set(extracted))  # Remove duplicates
        elif random.random() > 0.1:
            allergies = [AllergyFactory() for _ in range(3)]
        else:
            allergies = []

        for allergy in allergies:
            if allergy not in self.allergies.all():
                self.allergies.add(allergy)

    @factory.post_generation
    def personal_recipes(self, create, extracted):
        if not create:
            # do nothing.
            return

        if extracted:
            for recipe in extracted:
                self.personal_recipes.add(recipe)
        else:
            recipes = [RecipeFactory(profile=self) for _ in range(random.randint(2, 5))]
            for recipe in recipes:
                recipe_ingredients = MockRecipe.objects.filter(
                    m_recipe_name=recipe.recipe_name).first().m_ingredients.all()
                ingredients = [ri.ingredient for ri in recipe_ingredients]
                recipe.ingredients.set(ingredients)
                try:
                    recipe.save()
                    self.personal_recipes.add(recipe)
                except ValidationError as e:
                    # Handle the validation error gracefully
                    print(f"Error saving recipe: {e}")

    @classmethod
    def favorite_recipes(cls, profile, create=True, num_people=100, max_favorites=3):
        if not create:
            return []

        if not profile.id:
            profile.save()

        # Choose a random set of profiles
        profiles = Profile.objects.exclude(id=profile.id).order_by('?')[:num_people]

        # Choose a random set of favorite recipes for each profile
        favorites = []
        for p in profiles:
            recipes = Recipe.objects.filter(profile_id=p).order_by('?')[:max_favorites]
            favorites += [RecipeFavorite(profile=profile, recipe=r) for r in recipes]

        return favorites


```

Now let's move on to the gen_user.py file. This file is a Django management command that creates a new user profile and populates it with data using the factory classes defined in factory.py. It first creates a new Profile instance using ProfileFactory, and then generates three allergies for the profile using AllergyFactory.

Next, it generates a random number of personal recipes for the profile using RecipeFactory. It creates a Recipe instance for each recipe and adds it to the personal_recipes list. It then creates a new RecipePersonal instance for each recipe and associates it with the profile. Finally, it sets the personal_recipes attribute of the profile to the personal_recipes list.

The command then selects a random set of favorite recipes for the profile from all other profiles using the Recipe.objects.exclude() method. It creates a new RecipeFavorite instance for each favorite recipe and associates it with the profile. Finally, it sets the favorite_recipes attribute of the profile to the set of favorite recipes.

**gen_user.py:**
```python
import random
from django.core.management.base import BaseCommand
from ...models import MockRecipe, RecipeFavorite, RecipePersonal, Recipe
from ...factory import ProfileFactory, AllergyFactory, RecipeFactory


class Command(BaseCommand):
    help = 'add help command here'

    def handle(self, *args, **options):
        # Create a new Profile object with add_allergies keyword argument
        profile = ProfileFactory.create()

        # Generate allergy(s) for new Profile
        allergies = AllergyFactory.create_batch(3)
        profile.allergies.set(allergies)
        profile.save()

        # Generate personal recipes for profile
        personal_recipes = []
        for i in range(random.randint(2, 5)):
            recipe = RecipeFactory.create()
            personal_recipes.append(recipe)
            RecipePersonal.objects.create(profile=profile, recipe=recipe)
        profile.personal_recipes.set(personal_recipes)
        profile.save()

        # Select other profile's recipes as favorites
        favorite_recipes = Recipe.objects.exclude(profile=profile).order_by('?')[:random.randint(1, 5)]
        profile.favorite_recipes.set(favorite_recipes)
        profile.save()

        # Create RecipeFavorite objects for personal and favorite recipes
        for recipe in personal_recipes:
            RecipeFavorite.objects.create(profile=profile, recipe=recipe)
        for recipe in favorite_recipes:
            RecipeFavorite.objects.create(profile=profile, recipe=recipe)

```

Command to run **gen_users.py**:

```bash
python3 manage.py gen_user
```

**Error** that is returned:

```bash
Traceback (most recent call last):

ValueError: "<Profile: Profile object (None)>" needs to have a value for field "profile_id" before this many-to-many relationship can be used.

```

- I have put about 24 hours of actual seat time working on the above code and it's so close to being done that we can't let this error derail loading our db this way because I believe doing it in a dynamic way is the only rational way to fill our db. 

- How can you contribute? 
     - Clone this branch into a new branch and try fixing the error in the new branch.
     - I would be more than happy to troubleshoot it together over a discord call, so we are both sharing ideas.
 
@robert-daniels 
@yassine022 
@ArcadeZeus

**Comment by tswhitworth** [comment]
Please leave this issue open while the Error still exists.

**Comment by robert-daniels** [comment]
@yassine022 , @tswhitworth , unless this was closed by fix I'm re-opening.

**Comment by robert-daniels** [comment]
Error [IS] reproducible. Created branch : "issue32"

**Comment by robert-daniels** [comment]
@tswhitworth , line 71 in models.py. Were you planning on this one being an auto-generated primary key or hardcoded integer. You're generating a first name and last name, but the Profile class doesn't appear to be set to AutoField and instead wants a set value. 

![image](https://user-images.githubusercontent.com/11677947/223273306-f3203e3e-3a56-4255-95ba-862065f9fa62.png)

**Comment by tswhitworth** [comment]
Resolved issue ✅

updated: [factory.py](https://github.com/robert-daniels/CartBuilder/blob/test-vue-factory-testing/CartBuilderApplication/CartBuilder/factory.py)

updated: [gen_user2](https://github.com/robert-daniels/CartBuilder/blob/test-vue-factory-testing/CartBuilderApplication/CartBuilder/management/commands/gen_user2.py)

https://user-images.githubusercontent.com/124627883/223924430-610d5b58-aa11-47bd-be0d-e6ac857e370e.mov
