### ISSUE TITLE
Simple Database

### ISSUE THREAD

**Issue by tswhitworth** [robert-daniels/CartBuilder#35]
Please do not put any more time into developing the simple database. I will change my import_csv parser and models.py file to make it so we are parsing out the cooking instructions, and saving them in the database. 

Having our database fragmented is not okay and it needs to be unified or everything will not be able to function properly. 

I understand it was just for show to make things start working, but I don't want to go any further down this path.

**Comment by tswhitworth** [comment]
I have updated import_csv command so that it now parses the cooking instructions and saves it to MockInstruction.

I also updated our Models.py file so that we're saving these newly parsed values to the newly created MockInstruction class where import_csv saves all the cooking instructions, and I also added an Instruction class, and a field called instructions onto our Recipe model. 

I made a video of me running the import_csv command and showing exactly what I changed:

https://user-images.githubusercontent.com/124627883/227102545-0a7c91d9-1efd-4864-9d8a-24f7f016aafb.mp4

**Comment by tswhitworth** [comment]
@robert-daniels My next plan of action would be to start replicating what you have going in your simple database, so that you can just start using my functions instead without having to change any of your frontend code.

Feel free to get back to me on this whenever you're free over the next few days.

**Comment by robert-daniels** [comment]
![Screenshot_20230323-054331](https://user-images.githubusercontent.com/11677947/227179389-f26499e5-235d-4584-a2fb-7ed434d1fe46.png)
The files in question. There's no real front end code attached to these simple tables beyond a for loop

**Comment by robert-daniels** [comment]
closing, no longer applicable
