### ISSUE TITLE
Decide on functionality to track - Overview

### ISSUE THREAD

**Issue by robert-daniels** [robert-daniels/CartBuilder#6]
With the recipe / cart application, we'll need to define the scope that's possible for the semester. 

We would likely need: 
User profile
Session tracking
Database of recipes
Porting recipe to the shopping list
UI for the shopping list

Other possibilities : 
Select a list of recipes from database that match products user reports in their kitchen / would like to build around
Sign in with Facebook / Google 
Maps to grocery stores (Google mapsAPI) 

We can use the Recipies1m+ JSON dataset to populate the database once set up.

**Comment by dghighfill** [comment]
Can't wait this the first PO meeting.  What your building sounds really neat.

**Comment by robert-daniels** [comment]
No longer outstanding issue
