### ISSUE TITLE
MVC allocation

### ISSUE THREAD

**Issue by robert-daniels** [robert-daniels/CartBuilder#7]
In terms of work allocation, 

Model : Ryan has stated he would like to work more on the database side

View: Does anyone have much experience with Bootstrap or similar html / css frameworks? I can work on this one if need be.

Controller : Dependent on our framework and language choices. I have more of a background with PHP and JavaScript than others. 

Any other thoughts for this?

**Comment by tswhitworth** [comment]
My biggest strength to lowest strength (dev wise) is backend, frontend, database.

It sounds like the **Model** portion is covered by Ryan, awesome. 

@robert-daniels would you be open to working on the **View** portion predominately? 

I would love to take on the **Controller** portion of the project, but am open to working where ever, but I do think the backend/API portion would be a good fit for me.

@yassine022 is there any portion of this project that you would really like to work on in particular? I'm trying to think how we can best split this work up among the 4 of us and would love to hear what interests you.

I also have some experience with HTML/CSS and Javascript/Typescript so I would be able to help on the View as well.

**Comment by robert-daniels** [comment]
@tswhitworth I can focus more on the view side! More of my background has been with Node.js / templating anyway. Type safety would be nice with TypeScript, though I'm not sure we all have strongly typed language experience.

**Comment by yassine022** [comment]
I can focus on the backend/API side.

**Comment by robert-daniels** [comment]
Marking as closed
